//! Native resolver -> authenticated transport -> real MP3 decoder -> TCP PCM.
//! Uses a synthetic fixture generated by CI; no Emby server or audio device.
use super::*;
use migration::{Migrator, MigratorTrait};
use music_player_storage::{saved_servers, Database};
use music_player_types::source::RemoteIdentity;
use rockbox_playback::{PlayerConfig, StreamOutputBoundary};
use serde_json::json;
use std::sync::{Arc, Mutex};
use tokio::{
    io::{AsyncReadExt, AsyncWriteExt},
    net::{TcpListener, TcpStream},
};

const AUDIO: &[u8] = include_bytes!("../../tests/fixtures/tone-2s.mp3");

async fn request(socket: &mut TcpStream) -> (String, String, String) {
    let mut bytes = Vec::new();
    let mut buffer = [0; 2048];
    let end = loop {
        if let Some(end) = bytes.windows(4).position(|p| p == b"\r\n\r\n") {
            break end + 4;
        }
        assert!(bytes.len() < 65536);
        let n = socket.read(&mut buffer).await.unwrap();
        assert_ne!(n, 0);
        bytes.extend_from_slice(&buffer[..n]);
    };
    let headers = String::from_utf8(bytes[..end].to_vec()).unwrap();
    let length: usize = headers
        .lines()
        .find_map(|line| {
            let (key, value) = line.split_once(':')?;
            key.eq_ignore_ascii_case("content-length")
                .then(|| value.trim().parse().unwrap())
        })
        .unwrap_or(0);
    assert!(length < 65536);
    while bytes.len() < end + length {
        let n = socket.read(&mut buffer).await.unwrap();
        assert_ne!(n, 0);
        bytes.extend_from_slice(&buffer[..n]);
    }
    let mut line = headers.lines().next().unwrap().split_ascii_whitespace();
    (
        line.next().unwrap().into(),
        line.next().unwrap().into(),
        headers,
    )
}

#[tokio::test]
async fn native_audio_reaches_pcm_with_auth_and_eof_retains_the_pinned_checkpoint() {
    tokio::time::timeout(Duration::from_secs(30), async {
        let connection = sea_orm::Database::connect("sqlite::memory:").await.unwrap();
        Migrator::up(&connection, None).await.unwrap();
        let db = Database { connection };
        let http = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let url = format!("http://{}", http.local_addr().unwrap());
        let account = saved_servers::upsert(db.get_connection(),
            &saved_servers::NewServer::new("emby", "CI Emby", &url)
                .with_credentials(Some("family".into()), None)
                .with_password_update(saved_servers::PasswordUpdate::Set(String::new())),
            "2026-09-30T12:00:00Z").await.unwrap();
        let remote = RemoteIdentity { server_id: "server-a".into(), user_id: "user-a".into() };
        saved_servers::bind_remote_identity(db.get_connection(), &account, &remote).await.unwrap();
        let source = SourceRef { resolver: "emby".into(), account_id: account.id,
            remote, kind: ResourceKind::Item, item_id: "55508".into() };
        let requests = Arc::new(Mutex::new(Vec::new()));
        let recorded = requests.clone();
        let server = tokio::spawn(async move {
            loop {
                let (mut socket, _) = http.accept().await.unwrap();
                let (method, target, headers) = request(&mut socket).await;
                let path = target.split('?').next().unwrap();
                let body = match (method.as_str(), path) {
                    ("POST", "/Users/AuthenticateByName") => serde_json::to_vec(&json!({
                        "AccessToken":"synthetic-token", "ServerId":"server-a", "User":{"Id":"user-a"}
                    })).unwrap(),
                    ("GET", "/Users/user-a/Items/55508") => serde_json::to_vec(&json!({
                        "Id":"55508", "Name":"Synthetic episode", "Type":"Episode", "MediaType":"Video",
                        "RunTimeTicks":191429666670_u64, "IsFolder":false
                    })).unwrap(),
                    ("GET", "/Items/55508/PlaybackInfo") => serde_json::to_vec(&json!({
                        "PlaySessionId":"session-ci", "MediaSources":[{
                            "Id":"version-a", "RunTimeTicks":191429666670_u64,
                            "DefaultAudioStreamIndex":1, "MediaStreams":[
                                {"Type":"Video", "Index":0, "Codec":"h264"},
                                {"Type":"Audio", "Index":1, "Codec":"aac", "IsDefault":false}
                            ]
                        }]
                    })).unwrap(),
                    ("GET", "/Audio/55508/stream.mp3") => {
                        assert!(target.contains("AudioStreamIndex=1"));
                        assert!(target.contains("StartTimeTicks=72001230000"));
                        assert!(target.contains("EnableAutoStreamCopy=false"));
                        AUDIO.to_vec()
                    },
                    ("DELETE", "/Videos/ActiveEncodings") => {
                        assert!(target.contains("PlaySessionId=session-ci"));
                        assert!(target.contains("DeviceId=host-ci"));
                        b"{}".to_vec()
                    },
                    _ => panic!("unexpected fixture request"),
                };
                if method != "POST" {
                    assert!(headers.lines().any(|line| line.split_once(':').is_some_and(|(key, value)|
                        key.eq_ignore_ascii_case("x-emby-token") && value.trim() == "synthetic-token")));
                }
                recorded.lock().unwrap().push((method.clone(), path.to_owned()));
                let content_type = if path.ends_with(".mp3") { "audio/mpeg" } else { "application/json" };
                let response = format!("HTTP/1.1 200 OK\r\nContent-Type: {content_type}\r\nContent-Length: {}\r\nConnection: close\r\n\r\n", body.len());
                socket.write_all(response.as_bytes()).await.unwrap();
                socket.write_all(&body).await.unwrap();
                socket.shutdown().await.unwrap();
                if method == "DELETE" { break; }
            }
        });
        let pcm = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let output = format!("tcp:{}", pcm.local_addr().unwrap()).parse().unwrap();
        let received = Arc::new(Mutex::new(Vec::new()));
        let collected = received.clone();
        let collector = tokio::spawn(async move {
            let (mut socket, _) = pcm.accept().await.unwrap();
            let mut buffer = [0; 8192];
            loop {
                let count = socket.read(&mut buffer).await.unwrap();
                if count == 0 { break; }
                let mut bytes = collected.lock().unwrap();
                assert!(bytes.len() + count < 2_000_000);
                bytes.extend_from_slice(&buffer[..count]);
            }
        });
        let engine = Engine::with_config(PlayerConfig {
            output, sample_rate: Some(44100), buffer_seconds: 1.0, ..Default::default()
        }).unwrap();
        let mut player = SourcePlayback::new(SourceResolver::new(db, "host-ci".into(), true));
        player.load(source, Duration::from_millis(7_200_123), true).unwrap();
        loop {
            player.poll(&engine);
            assert_ne!(player.snapshot().phase, Phase::Failed, "host audio failed");
            if player.snapshot().phase == Phase::EndUnconfirmed
                && player.snapshot().position.is_some()
                && received.lock().unwrap().iter().any(|byte| *byte != 0)
                && server.is_finished() { break; }
            tokio::time::sleep(Duration::from_millis(10)).await;
        }
        server.await.unwrap();
        let snapshot = player.snapshot();
        let position = snapshot.position.unwrap();
        assert_eq!(position.boundary, StreamOutputBoundary::ByteStream);
        assert_eq!(position.start, StartPosition::RequestedOnly);
        assert!(position.absolute > Duration::from_millis(7_200_123));
        assert!(position.absolute < Duration::from_millis(7_205_123));
        assert_eq!(snapshot.phase, Phase::EndUnconfirmed);
        assert!(player.is_loaded());
        let checkpoint = player.checkpoint().unwrap();
        assert!(matches!(&checkpoint.selection, AudioSelection::Pinned(pin) if pin.audio_stream_index == 1));
        assert_eq!(requests.lock().unwrap().len(), 5);
        player.pause();
        engine.stop();
        let paused = player.checkpoint().unwrap();
        assert!(paused.offset_ms >= checkpoint.offset_ms);
        assert_eq!(paused.selection, checkpoint.selection);
        assert!(player.task.is_none());
        drop(player);
        drop(engine);
        collector.await.unwrap();
    }).await.expect("host MP3 fixture exceeded deadline");
}
